### ISSUE TITLE
code release

### ISSUE THREAD

**Issue by whwh747** [hjr37/CG-SLAM#1]
Thank you very much for your extraordinary work. Is there a release date for the code?

**Comment by hjr37** [comment]
Thank you for your attention. We are organizing and clearing our code. We expect to release the entire system framework by early July at the latest. We have currently made some core components in CG-SLAM available ([https://github.com/hjr37/diff-gaussian-rasterization](https://github.com/hjr37/diff-gaussian-rasterization)), hoping they will be helpful to you.

**Comment by whwh747** [comment]
thank you very much！
